"""
services.io - Route Import/Export Services
SVG and G-code importer/exporter implementations
"""

import os
from typing import List, Tuple, Optional, Dict, Any

from services.io.io_interfaces import IRouteExporter
from svg.tangential import routes_to_gcode


class GCodeExporter(IRouteExporter):
    """G-code file exporter using tangential.py module"""

    @property
    def name(self) -> str:
        return "G-Code Exporter"

    @property
    def file_extensions(self) -> List[str]:
        return ['.gcode', '.nc', '.cnc']

    @property
    def file_description(self) -> str:
        return "G-Code files"

    @property
    def default_extension(self) -> str:
        return '.gcode'

    def export_routes(self,
                      routes: List[List[Tuple[float, float]]],
                      output_file: str,
                      **kwargs) -> bool:
        """Export routes to G-code file using tangential module"""
        try:
            if not routes:
                return False

            # Extract parameters with defaults
            speed = kwargs.get('speed', 1500)
            cut_depth = kwargs.get('cut_depth', -1.0)
            safety_height = kwargs.get('safety_height', 5.0)
            initial_rotation = kwargs.get('initial_rotation', 0)
            offset = kwargs.get('offset', 2.75)
            angle_threshold = kwargs.get('angle_threshold', 30)

            gcode_lines = []

            # Process each route separately using tangential
            for route in routes:
                if len(route) >= 2:  # Need at least 2 points
                    route_gcode = routes_to_gcode(
                        points=route,
                        speed=speed,
                        cut_depth=cut_depth,
                        safety_height=safety_height,
                        initial_rotation=initial_rotation,
                        offset=offset,
                        angle_threshold=angle_threshold
                    )
                    gcode_lines.extend(route_gcode)

            # Add ending commands
            gcode_lines.append(f"G0 Z{safety_height} ; Raise to safety height")
            gcode_lines.append("G0 X0 Y0 ; Return to origin")
            gcode_lines.append("M2 ; End program")

            # Write to file
            with open(output_file, 'w') as f:
                f.write(f"; Generated by G-Code Exporter\n")
                f.write(f"; Routes: {len(routes)}, Speed: {speed} mm/min\n")
                f.write(f"; Cut depth: {cut_depth}mm, Safety: {safety_height}mm\n")
                f.write("\n")

                for line in gcode_lines:
                    f.write(line + "\n")

            return True

        except Exception:
            return False

    def get_export_options(self) -> Dict[str, Any]:
        """Get default G-code export options"""
        return {
            'speed': 1500,
            'cut_depth': -1.0,
            'safety_height': 5.0,
            'initial_rotation': 0,
            'offset': 2.75,
            'angle_threshold': 30
        }