# services/io/format_gcode.py (Updated with X Y offset support)
"""
G-Code Exporter with X Y Offset Support
"""

import os
from typing import List, Tuple, Optional, Dict, Any

from services.io.form_interface import IFormSchemaProvider
from services.io.io_interfaces import IRouteExporter
from svg.tangential import routes_to_gcode


class GCodeExporter(IRouteExporter, IFormSchemaProvider):
    """G-code file exporter with X Y offset capability"""

    @property
    def name(self) -> str:
        return "G-Code Exporter"

    @property
    def file_extensions(self) -> List[str]:
        return ['.gcode', '.nc', '.cnc']

    @property
    def file_description(self) -> str:
        return "G-Code files"

    @property
    def default_extension(self) -> str:
        return '.gcode'

    def export_routes(self,
                      routes: List[List[Tuple[float, float]]],
                      output_file: str,
                      **kwargs) -> bool:
        """Export routes to G-code file with optional X Y offset"""
        try:
            if not routes:
                return False

            # Extract parameters with defaults
            speed = kwargs.get('speed', 1500)
            cut_depth = kwargs.get('cut_depth', -1.0)
            safety_height = kwargs.get('safety_height', 5.0)
            initial_rotation = kwargs.get('initial_rotation', 0)
            offset = kwargs.get('offset', 2.75)
            angle_threshold = kwargs.get('angle_threshold', 30)

            # NEW: X Y offset parameters
            offset_x = kwargs.get('offset_x', 0.0)
            offset_y = kwargs.get('offset_y', 0.0)

            # Apply X Y offset to routes if specified
            if offset_x != 0.0 or offset_y != 0.0:
                routes = self._apply_xy_offset(routes, offset_x, offset_y)

            gcode_lines = []

            # Process each route separately using tangential
            for route in routes:
                if len(route) >= 2:  # Need at least 2 points
                    route_gcode = routes_to_gcode(
                        points=route,
                        speed=speed,
                        cut_depth=cut_depth,
                        safety_height=safety_height,
                        initial_rotation=initial_rotation,
                        offset=offset,
                        angle_threshold=angle_threshold
                    )
                    gcode_lines.extend(route_gcode)

            # Add ending commands
            gcode_lines.append(f"G0 Z{safety_height} ; Raise to safety height")
            gcode_lines.append("G0 X0 Y0 ; Return to origin")
            gcode_lines.append("M2 ; End program")

            # Write to file
            with open(output_file, 'w') as f:
                f.write(f"; Generated by G-Code Exporter\n")
                f.write(f"; Routes: {len(routes)}, Speed: {speed} mm/min\n")
                f.write(f"; Cut depth: {cut_depth}mm, Safety: {safety_height}mm\n")
                if offset_x != 0.0 or offset_y != 0.0:
                    f.write(f"; Applied offset: X{offset_x:.3f} Y{offset_y:.3f}\n")
                f.write("\n")

                for line in gcode_lines:
                    f.write(line + "\n")

            return True

        except Exception:
            return False

    def _apply_xy_offset(self, routes: List[List[Tuple[float, float]]],
                        offset_x: float, offset_y: float) -> List[List[Tuple[float, float]]]:
        """Apply X Y offset to all route points"""
        offset_routes = []
        for route in routes:
            offset_route = []
            for x, y in route:
                offset_route.append((x + offset_x, y + offset_y))
            offset_routes.append(offset_route)
        return offset_routes

    def get_export_options(self) -> Dict[str, Any]:
        """Get default G-code export options with X Y offset"""
        return {
            'speed': 1500,
            'cut_depth': -1.0,
            'safety_height': 5.0,
            'initial_rotation': 0,
            'offset': 2.75,
            'angle_threshold': 30,
            'offset_x': 0.0,
            'offset_y': 0.0
        }

    def get_form_schema(self) -> Optional[Dict[str, Any]]:
        """Get G-Code export form schema with X Y offset fields"""
        return {
            "title": "G-Code Export Options",
            "width": 350,
            "height": 450,  # Increased height for new fields
            "sections": [
                {
                    "title": "Position Offset",
                    "fields": [
                        {
                            "name": "offset_x",
                            "type": "float",
                            "label": "X Offset (mm):",
                            "default": 0.0,
                            "width": 12,
                            "help": "Shift all coordinates in X direction"
                        },
                        {
                            "name": "offset_y",
                            "type": "float",
                            "label": "Y Offset (mm):",
                            "default": 0.0,
                            "width": 12,
                            "help": "Shift all coordinates in Y direction"
                        }
                    ]
                },
                {
                    "title": "Motion Parameters",
                    "fields": [
                        {
                            "name": "speed",
                            "type": "number",
                            "label": "Feed Rate (mm/min):",
                            "default": 1500,
                            "width": 12
                        },
                        {
                            "name": "cut_depth",
                            "type": "float",
                            "label": "Cut Depth (mm):",
                            "default": -1.0,
                            "width": 12
                        },
                        {
                            "name": "safety_height",
                            "type": "float",
                            "label": "Safety Height (mm):",
                            "default": 5.0,
                            "width": 12
                        }
                    ]
                },
                {
                    "title": "Knife Parameters",
                    "fields": [
                        {
                            "name": "initial_rotation",
                            "type": "number",
                            "label": "Initial Rotation (degrees):",
                            "default": 0,
                            "width": 12
                        },
                        {
                            "name": "offset",
                            "type": "float",
                            "label": "Knife Offset (mm):",
                            "default": 2.75,
                            "width": 12
                        },
                        {
                            "name": "angle_threshold",
                            "type": "number",
                            "label": "Angle Threshold (degrees):",
                            "default": 30,
                            "width": 12
                        }
                    ]
                }
            ]
        }